/**
 * Content extraction using Defuddle + linkedom + Turndown.
 *
 * Uses a pre-bundled ESM version of `defuddle/node` to avoid CJS compatibility
 * issues in workerd (both wrangler dev and vitest-pool-workers).
 *
 * The bundle is generated by `scripts/bundle-defuddle.mjs` and includes:
 * - Defuddle core (content extraction)
 * - linkedom (DOM parsing + polyfills via linkedom-compat)
 * - Turndown (HTML → Markdown conversion)
 *
 * Rebuild after upgrading defuddle: `node scripts/bundle-defuddle.mjs`
 */

// @ts-expect-error -- pre-bundled ESM, no type declarations
import defuddleExports from "../lib/defuddle-bundle.mjs";
const { Defuddle } = defuddleExports;

export interface ExtractedContent {
  fullText: string | null;
  ogImage: string | null;
  excerpt: string | null;
  title: string | null;
}

/**
 * Extract article content from HTML using Defuddle.
 * Falls back to rssExcerpt if extraction fails or returns too little content.
 */
export async function extractContent(
  html: string,
  articleUrl: string,
  options?: { fallbackContent?: string | undefined },
): Promise<ExtractedContent> {
  if (!html || html.trim().length === 0) {
    return fallbackResult(options?.fallbackContent);
  }

  try {
    const result = await Defuddle(html, articleUrl, { markdown: true });

    const fullText = result.content || null;
    const ogImage = result.image && result.image.length > 0 ? result.image : null;
    const title = result.title && result.title.length > 0 ? result.title : null;

    let excerpt: string | null = null;
    if (fullText) {
      const plain = fullText
        .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
        .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
        .replace(/\s+/g, " ")
        .trim();
      excerpt = plain.slice(0, 200).trim() || null;
    }

    if (!fullText || fullText.trim().length < 50) {
      if (options?.fallbackContent) {
        return {
          fullText: options.fallbackContent,
          ogImage,
          excerpt: options.fallbackContent.slice(0, 200).trim() || null,
          title,
        };
      }
    }

    return { fullText, ogImage, excerpt, title };
  } catch {
    return fallbackResult(options?.fallbackContent);
  }
}

function fallbackResult(fallbackContent?: string): ExtractedContent {
  if (fallbackContent) {
    return {
      fullText: fallbackContent,
      ogImage: null,
      excerpt: fallbackContent.slice(0, 200).trim() || null,
      title: null,
    };
  }
  return { fullText: null, ogImage: null, excerpt: null, title: null };
}
