/**
 * Content extraction using Defuddle + linkedom + Turndown.
 *
 * Uses a pre-bundled ESM version of `defuddle/node` to avoid CJS compatibility
 * issues in workerd (both wrangler dev and vitest-pool-workers).
 *
 * The bundle is generated by `scripts/bundle-defuddle.mjs` and includes:
 * - Defuddle core (content extraction)
 * - linkedom (DOM parsing + polyfills via linkedom-compat)
 * - Turndown (HTML → Markdown conversion)
 *
 * Rebuild after upgrading defuddle: `node scripts/bundle-defuddle.mjs`
 */

// @ts-expect-error -- pre-bundled ESM, no type declarations
import defuddleExports from "../lib/defuddle-bundle.mjs";
const { Defuddle } = defuddleExports;

export interface ExtractedContent {
  fullText: string | null;
  ogImage: string | null;
  excerpt: string | null;
  title: string | null;
}

/**
 * Extract article content from HTML using Defuddle.
 * Falls back to rssExcerpt if extraction fails or returns too little content.
 */
export async function extractContent(
  html: string,
  articleUrl: string,
  options?: { fallbackContent?: string | undefined },
): Promise<ExtractedContent> {
  if (!html || html.trim().length === 0) {
    return fallbackResult(options?.fallbackContent);
  }

  try {
    const result = await Defuddle(html, articleUrl, { markdown: true });

    const fullText = result.content || null;
    const ogImage = result.image && result.image.length > 0 ? result.image : null;
    const title = result.title && result.title.length > 0 ? result.title : null;

    let excerpt: string | null = null;
    if (fullText) {
      const plain = fullText
        .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
        .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
        .replace(/\s+/g, " ")
        .trim();
      excerpt = plain.slice(0, 500).trim() || null;
    }

    if (!fullText || fullText.trim().length < 50) {
      // Defuddle couldn't find a content container — try raw body text as fallback.
      // This handles pages with flat structure (no <article>/<main> wrapper).
      const bodyText = extractBodyText(html);
      if (bodyText && bodyText.length >= 50) {
        const plainExcerpt =
          bodyText.replace(/\s+/g, " ").trim().slice(0, 500).trim() || null;
        return { fullText: bodyText, ogImage, excerpt: plainExcerpt, title };
      }
      if (options?.fallbackContent) {
        return {
          fullText: options.fallbackContent,
          ogImage,
          excerpt: options.fallbackContent.slice(0, 500).trim() || null,
          title,
        };
      }
    }

    return { fullText, ogImage, excerpt, title };
  } catch {
    return fallbackResult(options?.fallbackContent);
  }
}

/**
 * Extract plain text from <body>, stripping nav/header/footer/script/style.
 * Used when Defuddle fails to identify a content container.
 */
function extractBodyText(html: string): string | null {
  // Remove only elements that never contain article text.
  // Intentionally omit header/footer/nav/aside — some sites put content there.
  let cleaned = html
    .replace(/<(script|style|noscript)[^>]*>[\s\S]*?<\/\1>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "");
  // Extract body
  const bodyMatch = cleaned.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  if (!bodyMatch?.[1]) return null;
  // Strip remaining tags and decode entities
  const text = bodyMatch[1]
    .replace(/<[^>]*>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return text.length >= 50 ? text : null;
}

function fallbackResult(fallbackContent?: string): ExtractedContent {
  if (fallbackContent) {
    return {
      fullText: fallbackContent,
      ogImage: null,
      excerpt: fallbackContent.slice(0, 500).trim() || null,
      title: null,
    };
  }
  return { fullText: null, ogImage: null, excerpt: null, title: null };
}
